name: CI
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: joshdabosh/tf2-docker-comp,joshdabosh/tf2-docker-comp:sha-${{ github.sha }}
          cache-from: type=registry,ref=joshdabosh/tf2-docker-comp
          cache-to: type=inline
